apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythondeployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myflask
  template:
    metadata:
      labels:
        app: myflask
    spec:
      containers:
        - name: flaskapp
          image: deepak25404/python-flask:v1
          ports:
            - containerPort: 5000
