apiVersion: apps/v1
kind: Deployment
metadata:
  name: Flask
spec:
  selector:
    matchLabels:
      app: myflask
  template:
    metadata:
      labels:
        app: myflask
    spec:
      containers:
      - name: container1
        image: deepak25404/ip-flask
        ports:
        - containerPort: 5000
