apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskDeployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myflask
  template:
    metadata:
      labels:
        app: myflask
    spec:
      containers:
        - name: flask-app
          image: deepak25404/ip-flask:latest
          ports:
            - containerPort: 5000
