apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskDeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-app
          image: deepak25404/ip-flask:latest
          ports:
            - containerPort: 5000
