apiVersion: v1
kind: Service
metadata:
  name: flaskservice
  namespace: default
spec:
  type: NodePort
  selector:
    app: myflask
  ports:
  - name: mynodeport
    nodePort: 31111
    port: 80
    targetPort: 5000


    
