apiVersion: v1
kind: Service
metadata:
  name: flaskService
  namespace: flask
spec:
  type: NodePort
  selector:
    app: myflask
  ports:
  - name: my-nodeport
    nodePort: 31111
    port: 80
    targetPort: 5000


    
